openrewrite/rewrite-apache

- build.gradle.kts
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
Upgraded Apache HttpClient Dependency to 5.2.x
With this migration, we can able to migrate `org.apache.httpcomponents.core5:httpcore5` automatically without manual intervention.
@timtebeek
> Upgraded Apache HttpClient Dependency

- src/main/resources/META-INF/rewrite/apache-commons-collections-3-4.yml
- src/test/java/org/openrewrite/apache/commons/collections/UpgradeApacheCommonsCollections_3_4Test.java
Apache Commons Collections FastArrayList exists in 3.x, but does not exist in 4.x
Apache Commons Collections recipe
To make it easier to migrate to Apache Commons Collections 4.x
n/a
n/a
n/a
Commons Collections 4.x release notes
https://commons.apache.org/proper/commons-collections/release_4_0.html
> replace Apache Commons Collections FastArrayList

- src/main/java/org/openrewrite/apache/httpclient5/AddTimeUnitArgument.java
- src/main/java/org/openrewrite/apache/httpclient5/MigrateAuthScope.java
- src/main/java/org/openrewrite/apache/httpclient5/NewStatusLine.java
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/MigrateAuthScopeTest.java
- **Adding new migrations for Apache Http 4 to 5 client**
Add new recipes to migrate to migrate and fixes most of #2's compilation errors.
Migrate Apache http4 client applications
No.
No one.
N/A.
No.
> Adding new migrations for HTTP5 Client

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
Handle change in constructor signature for `HttpHost`.
See docs here:
(old version)
https://hc.apache.org/httpcomponents-core-4.4.x/current/httpcore/apidocs/org/apache/http/HttpHost.html
(new version)
https://hc.apache.org/httpcomponents-core-5.2.x/current/httpcore5/apidocs/org/apache/hc/core5/http/HttpHost.html
See 
We have handled this for our internal migration, so I just want to add this upstream so that others can use this.
Thank you for this automatic migration! 👍
> Handle change in constructor signature for `HttpHost`.

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
Apache HttpClient version:  5.2.x -> 5.3.x
Version 5.3.x is the latest release
https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5
n/a
n/a
n/a
n/a
> use Apache HttpClient 5.3.x

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
support Apache HttpClient 5.x ClassicRequestBuilder
https://hc.apache.org/httpcomponents-core-5.3.x/current/httpcore5/apidocs/org/apache/hc/core5/http/io/support/ClassicRequestBuilder.html
improve support for Apache HttpClient version 5.x
> use Apache HttpClient 5.x ClassicRequestBuilder

- src/main/resources/META-INF/rewrite/apache-poi-3-17.yml
Ensuring repositories with the current and proper group ID for `org.apache.poi:poi` will be updated to the latest minor of 3.x and not just the old group ID of `poi:poi`.  Also, includes an upgrade to artifact ID `poi-ooxml` which has a compile dependency of `poi`
Improving the outcomes of the recipe
N/A
@timtebeek 
N/A
N/A
> Upgrade all Apache POI dependencies to 3.17

- build.gradle.kts
- src/main/java/org/openrewrite/codehaus/plexus/AbstractLogEnabledToSlf4j.java
- src/main/java/org/openrewrite/codehaus/plexus/package-info.java
- src/test/java/org/openrewrite/codehaus/plexus/AbstractLogEnabledToSlf4jTest.java
https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=181305684#MavenEcosystemCleanup-DropPlexusContainerforJSR-330+SisuGuiceextension
Could have been manual, but that's no fun.
There's 574 calls to `AbstractLogEnabled *Log*(..)`
And then 721 calls to `org.codehaus.plexus.logging.Logger *(..)`
> Recipe to migrate from AbstractLogEnabled to SLF4J

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
`ProxyAuthenticationStrategy` doesn't exist in httpclient5 anymore.
Ref: https://stackoverflow.com/questions/76993237/how-to-set-proxyauthenticationstrategy-in-httpclientbuilder
> Migrate ProxyAuthenticationStrategy

- src/main/java/org/openrewrite/apache/httpclient5/UsernamePasswordCredentials.java
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
UsernamePasswordCredentials constructor signature is a little different
> Migrate UsernamePasswordCredentials

- src/main/java/org/openrewrite/apache/httpclient5/MigrateRequestConfig.java
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
I created a `MigrateRequestConfig` recipe for `RequestConfig`, it maybe complicated to finish.
Currently only `RequestConfig.Builder.setStaleConnectionCheckEnabled(false)` is migrated.
> Add MigrateRequestConfig

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
Change `ResponseHandler` to `HttpClientResponseHandler`, matching the change of `HttpResponse` to `ClassicHttpResponse`
> Change ResponseHandler to HttpClientResponseHandler

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
`org.apache.http.HttpMessage.getAllHeaders()` is moved to `org.apache.hc.core5.http.MessageHeaders.getHeaders()`
> Change getAllHeaders to getHeaders

- src/main/resources/META-INF/rewrite/apache-commons-collections-3-4.yml
- src/test/java/org/openrewrite/apache/commons/collections/UpgradeApacheCommonsCollections_3_4Test.java
- fixes #55
Ran into this while using the recipe on some code:)
Biggest thing is I'm worried this can't be 'blanket' done.  I asked on the original PR.  I've not used Apache commons collection a lot in my career.
- [x ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
Positive test added.  I read the guide once upon a time:)
> [55] Use `recursive: true` on ChangePackage for coll3->4 recipe

- src/main/resources/META-INF/rewrite/apache-commons-lang-3.yml
- src/test/java/org/openrewrite/apache/commons/lang/ApacheCommonsLang3UseStandardCharsetsTest.java
Created a new recipe to migrate the character encodings defined in `org.apache.commons.lang3.CharEncoding` to the java standard library implementation.
Partially addresses #4, the only thing remaining is the [isSupported](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/CharEncoding.html#isSupported(java.lang.String)) method. However that would require more thought as just calling [Charset#isSupported](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/charset/Charset.html#isSupported(java.lang.String)) due to the additional null/exception checks that occur within the apache method which mean that it isn't a direct drop in.
> Migrate `org.apache.commons.lang3.CharEncoding` to StandardCharsets

- build.gradle.kts
**What**:
Applying code suggestions, here adding `jspecify` dependency.
**Why**:
To save us from noise in unrelated PRs:
```
Some suggestions could not be made:
build.gradle.kts
lines 36-35
```
> Code suggestions

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
The declarative dependency `UpgradeApacheHttpClient_5`.
The recipe `org.openrewrite.apache.httpclient5.UpgradeApacheHttpClient_5` only [changes the HttpClient 4 dependency to the HttpClient 5 dependency](https://github.com/openrewrite/rewrite-apache/blob/main/src/main/resources/META-INF/rewrite/apache-httpclient-5.yml#L32-L43) if it has been declared as direct dependency. This is the case for Maven and Gradle projects.
Some projects may receive the HttpClient 4 dependency as a transitive dependency though. As a result, the imports are changed but the HttpClient 5 dependency has not been added leading to a compilation issue.
No
No
No
No
> Add HttpClient 5 dependency if it only existed transitively

- src/main/java/org/openrewrite/codehaus/plexus/AbstractLogEnabledToSlf4j.java
A minor change in the `AbstractLogEnabledToSlf4j`. Moving the `maybeAddImport` call after all `maybeRemoveImport` calls.
Following https://github.com/openrewrite/rewrite-testing-frameworks/pull/731
To fix one of the class of failures in the CI:
```
-    private static final Logger LOGGER = LoggerFactory.getLogger(A.class);
+    private static final org.slf4j.Logger LOGGER = LoggerFactory.getLogger(A.class);
```
> Moving addImport to the end of AbstractLogEnabledToSlf4j

- build.gradle.kts
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/main/resources/META-INF/rewrite/examples.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
Migrates the Apache's HttpComponents HttpMime for version 4 to HttpComponents HttpClient5
> Migrating Apache Http Components HttpMime into the Apache Http Client Client5

- src/main/resources/META-INF/rewrite/apache-commons-lang-2-3.yml
- src/test/java/org/openrewrite/apache/commons/lang/UpgradeApacheCommonsLang_2_3Test.java
Simple rename of a method between version of Apache Commons Lang
> Migrating `ExceptionUtils.getFullStackTrace(..)` to `ExceptionUtils.getStackTrace(..)`

- build.gradle.kts
- src/main/java/org/openrewrite/apache/httpclient5/ChangeArgumentToTimeValue.java
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/ChangeArgumentToTimeValueTest.java
- src/test/java/org/openrewrite/apache/httpclient5/MigrateApacheHttpCoreNioTest.java
For the Apache Http Components 4.x -> 5.x migration, `org.apache.http.impl.nio.reactor.IOReactorConfig` (within `httpcore-nio`) is getting migrated to `org.apache.hc.core5.http.impl.nio.reactor.IOReactorConfig` whereas it should be migrated to `org.apache.hc.core5.reactor.IOReactorConfig` (within `httpcore5`)
> Migrating `IOReactorConfig` from HttpCore Nio 4.4.x to HttpCore 5.x

- src/main/java/org/openrewrite/apache/httpclient5/MigrateRequestConfig.java
remove `Traits` factory method usage.
See https://github.com/openrewrite/rewrite-rewrite/pull/16
> Migrate Traits class usage to constructor calls

- src/main/resources/META-INF/rewrite/apache-httpclient-4-5.yml
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/UpgradeApacheHttpClient5Test.java
Prevented changing of the `org.apache.http.params` package and added a comment to the first relevant import indicating that manual migration will be necessary.
`org.apache.http.params.HttpParams`, along with all other classes in the `org.apache.http.params` package have been deprecated since at least version `4.3` of the Apache Http Client library (seen [here](https://hc.apache.org/httpcomponents-core-4.4.x/current/httpcore/apidocs/org/apache/http/params/package-summary.html)). In their stead, there are a number of configuration classes that would be used instead, but they are context specific to what content was being put into the `HttpParams` instance and can't be easily adequately inferred in many usages from a single codebase. Since we can't migrate it, it would be best to prevent the …
> Prevent changing of `org.apache.http.params` package (as there's no generic migration possible) and add a comment to that effect

- src/main/java/org/openrewrite/apache/httpclient5/NewRequestLine.java
- src/main/java/org/openrewrite/apache/httpclient5/NewStatusLine.java
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/apache/httpclient5/MigrateHttpResponseTest.java
- src/test/java/org/openrewrite/apache/httpclient5/NewRequestLineTest.java
- src/test/java/org/openrewrite/apache/httpclient5/NewStatusLineTest.java
The `org.apache.http.HttpResponse` in HttpClient 4.x needs to be migrated to `org.apache.hc.core5.http.ClassicHttpResponse` in HttpClient 5.x. The `ClassicHttpResponse` provides some backward-compatibility to the HttpClient 4.x API.
We already wanted to make that switch in our recipe list via
```
- org.openrewrite.java.ChangeType:
oldFullyQualifiedTypeName: org.apache.http.HttpRequest
newFullyQualifiedTypeName: org.apache.hc.core5.http.ClassicHttpRequest
- org.openrewrite.java.ChangeType:
oldFullyQualifiedTypeName: org.apache.http.HttpResponse
newFullyQualifiedTypeName: org.apache.hc.core5.http.ClassicHttpResponse
- org.openrewrite.java.ChangeType:
oldFullyQualifiedTypeName: org.apache.http.client.ResponseHandler
newFullyQualifiedTypeName: …
```
> Migrate `org.apache.http.HttpResponse` to `org.apache.hc.core5.http.ClassicHttpResponse`
